#!/usr/bin/env node
/**
 * sinain onboard — interactive setup wizard using @clack/prompts
 * Modeled after `openclaw onboard` for a familiar, polished experience.
 */
import * as p from "@clack/prompts";
import fs from "fs";
import path from "path";
import os from "os";
import net from "net";
import { execFileSync } from "child_process";

const HOME = os.homedir();
const SINAIN_DIR = path.join(HOME, ".sinain");
const ENV_PATH = path.join(SINAIN_DIR, ".env");
const PKG_DIR = path.dirname(new URL(import.meta.url).pathname);
const IS_WINDOWS = os.platform() === "win32";
const IS_MAC = os.platform() === "darwin";

// ── Colors ──────────────────────────────────────────────────────────────────

const c = {
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
};

// ── Helpers ─────────────────────────────────────────────────────────────────

function guard(value) {
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value;
}

function cmdExists(cmd) {
  try {
    execFileSync(IS_WINDOWS ? "where" : "which", [cmd], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function isPortOpen(port) {
  return new Promise((resolve) => {
    const sock = new net.Socket();
    sock.setTimeout(800);
    sock.on("connect", () => { sock.destroy(); resolve(true); });
    sock.on("error", () => resolve(false));
    sock.on("timeout", () => { sock.destroy(); resolve(false); });
    sock.connect(port, "127.0.0.1");
  });
}

function maskKey(key) {
  if (!key || key.length < 12) return "****";
  return key.slice(0, 8) + "..." + key.slice(-4);
}

/** Read existing .env into a key=value map */
function readEnv(envPath) {
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, "utf-8");
  const vars = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (val) vars[key] = val;
  }
  return vars;
}

/** Write vars to .env, preserving template structure */
function writeEnv(vars) {
  fs.mkdirSync(SINAIN_DIR, { recursive: true });

  const examplePath = path.join(PKG_DIR, ".env.example");
  let template = fs.existsSync(examplePath)
    ? fs.readFileSync(examplePath, "utf-8")
    : "";

  if (template) {
    for (const [k, v] of Object.entries(vars)) {
      const regex = new RegExp(`^#?\\s*${k}=.*$`, "m");
      if (regex.test(template)) {
        template = template.replace(regex, `${k}=${v}`);
      } else {
        template += `\n${k}=${v}`;
      }
    }
    template = `# Generated by sinain onboard — ${new Date().toISOString()}\n${template}`;
    fs.writeFileSync(ENV_PATH, template);
  } else {
    const lines = [
      "# sinain configuration",
      `# Generated by sinain onboard — ${new Date().toISOString()}`,
      "",
    ];
    for (const [k, v] of Object.entries(vars)) lines.push(`${k}=${v}`);
    lines.push("");
    fs.writeFileSync(ENV_PATH, lines.join("\n"));
  }
}

async function fetchHealth(port = 9500) {
  try {
    const res = await fetch(`http://127.0.0.1:${port}/health`, { signal: AbortSignal.timeout(2000) });
    return await res.json();
  } catch { return null; }
}

// ── Header ──────────────────────────────────────────────────────────────────

function printHeader() {
  console.log();
  console.log(c.bold("  ┌─────────────────────────────────────────┐"));
  console.log(c.bold("  │                                         │"));
  console.log(c.bold("  │") + c.cyan("    ╔═╗╦╔╗╔╔═╗╦╔╗╔  ╦ ╦╦ ╦╔╦╗        ") + c.bold("│"));
  console.log(c.bold("  │") + c.cyan("    ╚═╗║║║║╠═╣║║║║  ╠═╣║ ║ ║║        ") + c.bold("│"));
  console.log(c.bold("  │") + c.cyan("    ╚═╝╩╝╚╝╩ ╩╩╝╚╝  ╩ ╩╚═╝═╩╝        ") + c.bold("│"));
  console.log(c.bold("  │") + c.dim("      Privacy-first AI overlay          ") + c.bold("│"));
  console.log(c.bold("  │                                         │"));
  console.log(c.bold("  └─────────────────────────────────────────┘"));
  console.log();
}

// ── Steps ───────────────────────────────────────────────────────────────────

async function stepApiKey(existing, stepNum, totalSteps) {
  const current = existing.OPENROUTER_API_KEY;
  const message = current
    ? `[${stepNum}/${totalSteps}] OpenRouter API key ${c.dim(`(current: ${maskKey(current)})`)}`
    : `[${stepNum}/${totalSteps}] OpenRouter API key`;

  const key = guard(await p.text({
    message,
    placeholder: current ? "Press Enter to keep current" : "sk-or-v1-...",
    defaultValue: current || "",
    validate: (val) => {
      if (!val && !current) return "API key is required. Get one free at https://openrouter.ai/keys";
    },
  }));

  return key || current;
}

async function stepTranscription(existing) {
  const current = existing.TRANSCRIPTION_BACKEND || "openrouter";
  const hasWhisper = !IS_WINDOWS && cmdExists("whisper-cli");

  const choice = guard(await p.select({
    message: "[2/5] Audio transcription",
    options: [
      {
        value: "openrouter",
        label: "Cloud (OpenRouter)",
        hint: "Free, instant, no download",
      },
      {
        value: "local",
        label: "Local (Whisper)",
        hint: hasWhisper ? "whisper-cli detected on this machine" : "~1.5 GB download, fully private",
      },
    ],
    initialValue: current,
  }));

  if (choice === "local" && !hasWhisper && IS_MAC) {
    const install = guard(await p.confirm({
      message: "whisper-cli not found. Install via Homebrew?",
      initialValue: true,
    }));
    if (install) {
      const s = p.spinner();
      s.start("Installing whisper-cpp...");
      try {
        execFileSync("brew", ["install", "whisper-cpp"], { stdio: "pipe" });
        s.stop(c.green("whisper-cpp installed."));
      } catch {
        s.stop(c.yellow("Install failed — falling back to cloud."));
        return "openrouter";
      }
    }
  }

  return choice;
}

async function stepGateway(existing) {
  const choice = guard(await p.select({
    message: "[3/5] OpenClaw gateway (optional)",
    options: [
      {
        value: "skip",
        label: "Skip",
        hint: "sinain works standalone — add later with `sinain onboard --advanced`",
      },
      {
        value: "local",
        label: "Local gateway",
        hint: "Install & start openclaw on this machine",
      },
      {
        value: "remote",
        label: "Remote gateway",
        hint: "Connect to existing gateway (URL + token)",
      },
      {
        value: "nemoclaw",
        label: "NemoClaw",
        hint: "NVIDIA Brev cloud instance",
      },
    ],
    initialValue: existing.OPENCLAW_WS_URL ? "remote" : "skip",
  }));

  if (choice === "skip") {
    return {
      OPENCLAW_WS_URL: "",
      OPENCLAW_HTTP_URL: "",
      OPENCLAW_WS_TOKEN: "",
      OPENCLAW_HTTP_TOKEN: "",
      ESCALATION_MODE: "off",
    };
  }

  if (choice === "local") {
    return await setupLocalGateway(existing);
  }

  // remote or nemoclaw
  const urlHint = choice === "nemoclaw"
    ? "From Brev dashboard → Expose Port 18789"
    : "Example: ws://192.168.1.100:18789";

  const wsUrl = guard(await p.text({
    message: choice === "nemoclaw" ? "NemoClaw WebSocket URL" : "Gateway WebSocket URL",
    placeholder: urlHint,
    defaultValue: existing.OPENCLAW_WS_URL || "",
    validate: (val) => {
      if (!val) return "URL is required";
      if (!val.startsWith("ws://") && !val.startsWith("wss://")) return "Must start with ws:// or wss://";
    },
  }));

  const token = guard(await p.text({
    message: choice === "nemoclaw" ? "NemoClaw auth token" : "Gateway token (48-char hex)",
    placeholder: existing.OPENCLAW_WS_TOKEN ? "Press Enter to keep current" : "Paste token here",
    defaultValue: existing.OPENCLAW_WS_TOKEN || "",
  }));

  // Test connection
  const s = p.spinner();
  s.start("Testing gateway connection...");
  try {
    const parsed = new URL(wsUrl);
    const port = parseInt(parsed.port || "18789");
    const reachable = await isPortOpen(port);
    if (reachable) {
      s.stop(c.green("Gateway reachable."));
    } else {
      s.stop(c.yellow("Gateway not reachable — config saved anyway. Start it before running sinain."));
    }
  } catch {
    s.stop(c.yellow("Could not parse URL — config saved anyway."));
  }

  const httpUrl = wsUrl.replace(/^ws/, "http") + "/hooks/agent";
  return {
    OPENCLAW_WS_URL: wsUrl,
    OPENCLAW_HTTP_URL: httpUrl,
    OPENCLAW_WS_TOKEN: token,
    OPENCLAW_HTTP_TOKEN: token,
    OPENCLAW_SESSION_KEY: "agent:main:sinain",
    ESCALATION_MODE: "rich",
  };
}

async function setupLocalGateway(existing) {
  const hasOpenclaw = cmdExists("openclaw");

  if (!hasOpenclaw) {
    const install = guard(await p.confirm({
      message: "openclaw CLI not found. Install globally via npm?",
      initialValue: true,
    }));
    if (install) {
      const s = p.spinner();
      s.start("Installing openclaw...");
      try {
        execFileSync("npm", ["install", "-g", "openclaw@latest"], { stdio: "pipe", timeout: 120_000 });
        s.stop(c.green("openclaw installed."));
      } catch {
        s.stop(c.red("Installation failed."));
        p.note(
          "Install manually: npm install -g openclaw\nThen re-run: sinain onboard --advanced",
          "Manual install",
        );
        return {
          OPENCLAW_WS_URL: "",
          OPENCLAW_HTTP_URL: "",
          ESCALATION_MODE: "off",
        };
      }
    } else {
      return {
        OPENCLAW_WS_URL: "",
        OPENCLAW_HTTP_URL: "",
        ESCALATION_MODE: "off",
      };
    }
  }

  // Check if gateway is already running
  const s = p.spinner();
  s.start("Checking gateway...");
  const gatewayUp = await isPortOpen(18789);

  // Try to read existing token
  const ocJsonPath = path.join(HOME, ".openclaw/openclaw.json");
  let token = "";
  if (fs.existsSync(ocJsonPath)) {
    try {
      const ocConfig = JSON.parse(fs.readFileSync(ocJsonPath, "utf-8"));
      token = ocConfig.gateway?.auth?.token || "";
    } catch { /* ignore */ }
  }

  if (gatewayUp) {
    s.stop(c.green("Gateway already running (port 18789)."));
  } else {
    s.stop(c.yellow("Gateway not running."));
    p.note(
      "Start your gateway:\n  openclaw gateway run\n  or: openclaw onboard --install-daemon",
      "Next step",
    );
  }

  return {
    OPENCLAW_WS_URL: "ws://localhost:18789",
    OPENCLAW_HTTP_URL: "http://localhost:18789/hooks/agent",
    OPENCLAW_WS_TOKEN: token,
    OPENCLAW_HTTP_TOKEN: token,
    OPENCLAW_SESSION_KEY: "agent:main:sinain",
    ESCALATION_MODE: "rich",
  };
}

async function stepPrivacy(existing) {
  const current = existing.PRIVACY_MODE || "standard";
  const choice = guard(await p.select({
    message: "[4/5] Privacy mode",
    options: [
      {
        value: "standard",
        label: "Standard",
        hint: "Screen text sent to OpenRouter for OCR (auto-redacted: cards, keys, tokens)",
      },
      {
        value: "strict",
        label: "Strict",
        hint: "Only summaries leave your machine, no raw screen text",
      },
      {
        value: "paranoid",
        label: "Paranoid",
        hint: "Fully local — requires Whisper + Ollama",
      },
    ],
    initialValue: current,
  }));

  return choice;
}

async function stepModel(existing) {
  const current = existing.AGENT_MODEL || "google/gemini-2.5-flash-lite";
  const knownModels = ["google/gemini-2.5-flash-lite", "google/gemini-2.5-flash", "anthropic/claude-sonnet-4-6"];

  const choice = guard(await p.select({
    message: "[5/5] AI model for HUD analysis",
    options: [
      {
        value: "google/gemini-2.5-flash-lite",
        label: "gemini-2.5-flash-lite",
        hint: "Fast, cheap (recommended)",
      },
      {
        value: "google/gemini-2.5-flash",
        label: "gemini-2.5-flash",
        hint: "Better quality, slightly slower",
      },
      {
        value: "anthropic/claude-sonnet-4-6",
        label: "claude-sonnet-4-6",
        hint: "Anthropic via OpenRouter",
      },
      {
        value: "custom",
        label: "Custom",
        hint: "Enter a model ID from OpenRouter",
      },
    ],
    initialValue: knownModels.includes(current) ? current : "custom",
  }));

  if (choice === "custom") {
    const modelId = guard(await p.text({
      message: "Model ID (from openrouter.ai/models)",
      placeholder: "provider/model-name",
      defaultValue: knownModels.includes(current) ? "" : current,
      validate: (val) => {
        if (!val) return "Model ID is required";
        if (!val.includes("/")) return "Format: provider/model-name";
      },
    }));
    return modelId;
  }

  return choice;
}

async function stepOverlay(existing) {
  // Check if overlay is already installed
  const overlayPaths = [
    path.join(SINAIN_DIR, "overlay", "SinainHUD.app"),
    path.join(SINAIN_DIR, "overlay", "sinain_hud.exe"),
  ];
  const overlayInstalled = overlayPaths.some((p) => fs.existsSync(p));

  const choice = guard(await p.select({
    message: "Install overlay",
    options: [
      {
        value: "download",
        label: "Download pre-built app (recommended)",
        hint: "No Flutter SDK needed",
      },
      {
        value: "source",
        label: "Build from source",
        hint: "Requires Flutter SDK",
      },
      {
        value: "skip",
        label: overlayInstalled ? "Skip (already installed)" : "Skip for now",
        hint: overlayInstalled ? "SinainHUD.app detected" : "Install later: sinain setup-overlay",
      },
    ],
    initialValue: overlayInstalled ? "skip" : "download",
  }));

  if (choice === "download" || choice === "source") {
    const s = p.spinner();
    const label = choice === "download" ? "Downloading overlay..." : "Building overlay from source...";
    s.start(label);
    try {
      // setup-overlay.js handles both modes via process.argv
      if (choice === "source") process.argv.push("--from-source");
      await import("./setup-overlay.js");
      s.stop(c.green("Overlay installed."));
    } catch (err) {
      s.stop(c.yellow(`Failed: ${err.message}`));
      p.note("Install manually: sinain setup-overlay", "Overlay");
    }
  }
}

// ── Health check ────────────────────────────────────────────────────────────

async function runHealthCheck() {
  const checks = [];

  // sinain-core
  const coreUp = await isPortOpen(9500);
  if (coreUp) {
    checks.push(c.green("  sinain-core: reachable (port 9500)"));
    const health = await fetchHealth();
    if (health) {
      // Audio
      const audioState = health.audio?.state || health.audioPipeline?.state;
      if (audioState === "active" || audioState === "running") {
        checks.push(c.green("  Audio pipeline: active"));
      } else {
        checks.push(c.yellow("  Audio pipeline: inactive — check audio device settings"));
      }
      // Screen
      const screenActive = health.screen?.state === "active" || health.senseActive;
      if (screenActive) {
        checks.push(c.green("  Screen capture: active"));
      } else {
        if (IS_MAC) {
          checks.push(c.yellow("  Screen capture: inactive"));
          checks.push(c.dim("    Grant Screen Recording in System Settings → Privacy & Security"));
        } else {
          checks.push(c.yellow("  Screen capture: inactive"));
        }
      }
      // Gateway
      const gwConnected = health.escalation?.gatewayConnected;
      if (gwConnected) {
        checks.push(c.green("  OpenClaw gateway: connected"));
      } else if (health.escalation?.mode === "off") {
        checks.push(c.dim("  OpenClaw gateway: not configured (standalone mode)"));
      } else {
        checks.push(c.yellow("  OpenClaw gateway: not connected"));
      }
    }
  } else {
    checks.push(c.dim("  sinain-core: not running"));
    checks.push(c.dim("  Start with: sinain start (or ./start.sh)"));
  }

  if (checks.length > 0) {
    p.note(checks.join("\n"), "System health");
  }
}

// ── Main ────────────────────────────────────────────────────────────────────

export async function runOnboard(args = {}) {
  printHeader();
  p.intro("SinainHUD setup");

  const existing = readEnv(ENV_PATH);
  const hasExisting = Object.keys(existing).length > 0;

  // ── Existing config handling ────────────────────────────────────────────

  let configAction = "fresh";
  if (hasExisting) {
    const summary = [];
    if (existing.OPENROUTER_API_KEY) summary.push(`OPENROUTER_API_KEY: ${maskKey(existing.OPENROUTER_API_KEY)}`);
    if (existing.TRANSCRIPTION_BACKEND) summary.push(`TRANSCRIPTION_BACKEND: ${existing.TRANSCRIPTION_BACKEND}`);
    if (existing.ESCALATION_MODE) summary.push(`ESCALATION_MODE: ${existing.ESCALATION_MODE}`);
    if (existing.AGENT_MODEL) summary.push(`AGENT_MODEL: ${existing.AGENT_MODEL}`);
    if (existing.PRIVACY_MODE) summary.push(`PRIVACY_MODE: ${existing.PRIVACY_MODE}`);
    if (existing.OPENCLAW_WS_URL) summary.push(`OPENCLAW_WS_URL: ${existing.OPENCLAW_WS_URL}`);

    p.note(summary.join("\n"), "Existing config detected");

    configAction = guard(await p.select({
      message: "Config handling",
      options: [
        { value: "keep", label: "Use existing values" },
        { value: "update", label: "Update values" },
        { value: "reset", label: "Reset (start fresh)" },
      ],
      initialValue: "keep",
    }));

    if (configAction === "keep") {
      p.log.success("Using existing configuration.");
      await stepOverlay(existing);
      await runHealthCheck();
      printOutro();
      return;
    }

    if (configAction === "reset") {
      fs.unlinkSync(ENV_PATH);
      p.log.info("Config reset.");
    }
  }

  const base = configAction === "update" ? existing : {};

  // ── Flow selection ──────────────────────────────────────────────────────

  const flow = args.flow || guard(await p.select({
    message: "Setup mode",
    options: [
      {
        value: "quickstart",
        label: "QuickStart",
        hint: "Get running in 2 minutes. Configure details later.",
      },
      {
        value: "advanced",
        label: "Advanced",
        hint: "Full control over privacy, models, and connections.",
      },
    ],
    initialValue: "quickstart",
  }));

  const totalSteps = flow === "quickstart" ? 2 : 5;

  // ── Collect vars ────────────────────────────────────────────────────────

  const vars = { ...base };

  // Step 1: API key (both flows)
  const apiKey = await stepApiKey(base, 1, totalSteps);
  vars.OPENROUTER_API_KEY = apiKey;
  p.log.success("API key saved.");

  if (flow === "quickstart") {
    // QuickStart: sensible defaults
    vars.TRANSCRIPTION_BACKEND = base.TRANSCRIPTION_BACKEND || "openrouter";
    vars.PRIVACY_MODE = base.PRIVACY_MODE || "standard";
    vars.AGENT_MODEL = base.AGENT_MODEL || "google/gemini-2.5-flash-lite";
    vars.ESCALATION_MODE = base.ESCALATION_MODE || "off";
    vars.SINAIN_AGENT = base.SINAIN_AGENT || "claude";
    if (!vars.OPENCLAW_WS_URL) {
      vars.OPENCLAW_WS_URL = "";
      vars.OPENCLAW_HTTP_URL = "";
    }

    p.note(
      [
        `Transcription: ${vars.TRANSCRIPTION_BACKEND}`,
        `Privacy: ${vars.PRIVACY_MODE}`,
        `Model: ${vars.AGENT_MODEL}`,
        `Escalation: ${vars.ESCALATION_MODE}`,
        "",
        `Change later: sinain onboard --advanced`,
      ].join("\n"),
      "QuickStart defaults",
    );
  } else {
    // Advanced flow: steps 2-5
    const transcription = await stepTranscription(base);
    vars.TRANSCRIPTION_BACKEND = transcription;
    p.log.success(`Using ${transcription === "openrouter" ? "cloud" : "local"} transcription.`);

    if (transcription === "local") {
      const modelDir = path.join(HOME, "models");
      const modelPath = path.join(modelDir, "ggml-large-v3-turbo.bin");
      if (!fs.existsSync(modelPath)) {
        const download = guard(await p.confirm({
          message: "Download Whisper model (~1.5 GB)?",
          initialValue: true,
        }));
        if (download) {
          const s = p.spinner();
          s.start("Downloading Whisper model...");
          try {
            fs.mkdirSync(modelDir, { recursive: true });
            execFileSync("curl", [
              "-L", "--progress-bar",
              "-o", modelPath,
              "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo.bin",
            ], { stdio: "inherit" });
            s.stop(c.green("Model downloaded."));
            vars.LOCAL_WHISPER_MODEL = modelPath;
          } catch {
            s.stop(c.yellow("Download failed. You can download manually later."));
          }
        }
      } else {
        vars.LOCAL_WHISPER_MODEL = modelPath;
        p.log.info(`Whisper model found: ${c.dim(modelPath)}`);
      }
    }

    const gatewayVars = await stepGateway(base);
    Object.assign(vars, gatewayVars);
    if (gatewayVars.ESCALATION_MODE === "off") {
      p.log.info("Standalone mode (no gateway).");
    } else {
      p.log.success("Gateway configured.");
    }

    const privacy = await stepPrivacy(base);
    vars.PRIVACY_MODE = privacy;
    p.log.success(`Privacy: ${privacy}.`);

    const model = await stepModel(base);
    vars.AGENT_MODEL = model;
    p.log.success(`Model: ${model}.`);

    vars.SINAIN_AGENT = base.SINAIN_AGENT || "claude";
  }

  // ── Common defaults ───────────────────────────────────────────────────

  vars.SINAIN_CORE_URL = vars.SINAIN_CORE_URL || "http://localhost:9500";
  vars.SINAIN_POLL_INTERVAL = vars.SINAIN_POLL_INTERVAL || "5";
  vars.SINAIN_HEARTBEAT_INTERVAL = vars.SINAIN_HEARTBEAT_INTERVAL || "900";
  vars.AUDIO_CAPTURE_CMD = vars.AUDIO_CAPTURE_CMD || "screencapturekit";
  vars.AUDIO_AUTO_START = vars.AUDIO_AUTO_START || "true";
  vars.PORT = vars.PORT || "9500";

  // ── Write config ──────────────────────────────────────────────────────

  const s = p.spinner();
  s.start("Writing configuration...");
  writeEnv(vars);
  s.stop(c.green(`Config saved: ${c.dim(ENV_PATH)}`));

  // ── Overlay ───────────────────────────────────────────────────────────

  await stepOverlay(base);

  // ── Health check ──────────────────────────────────────────────────────

  await runHealthCheck();

  // ── What now ──────────────────────────────────────────────────────────

  printOutro();

  // ── Start? ────────────────────────────────────────────────────────────

  const startNow = guard(await p.confirm({
    message: "Start sinain now?",
    initialValue: true,
  }));

  if (startNow) {
    p.outro("Launching sinain...");
    try {
      await import("./launcher.js");
    } catch (err) {
      console.log(c.yellow(`  Launch failed: ${err.message}`));
      console.log(c.dim("  Try manually: sinain start"));
    }
  } else {
    p.outro("Run when ready: sinain start");
  }
}

function printOutro() {
  const hotkey = IS_WINDOWS ? "Ctrl+Shift" : "Cmd+Shift";
  p.note(
    [
      "Hotkeys:",
      `  ${hotkey}+Space — Show/hide overlay`,
      `  ${hotkey}+E     — Cycle tabs (Stream → Agent → Tasks)`,
      `  ${hotkey}+C     — Toggle click-through`,
      `  ${hotkey}+M     — Cycle display mode`,
      "",
      "Docs: https://github.com/geravant/sinain-hud",
      "Re-run: sinain onboard (or sinain onboard --advanced)",
    ].join("\n"),
    "What now",
  );
}

// ── CLI entry point ─────────────────────────────────────────────────────────

const cliArgs = process.argv.slice(2);
const flags = {};
for (const arg of cliArgs) {
  if (arg === "--advanced") flags.flow = "advanced";
  if (arg === "--quickstart") flags.flow = "quickstart";
  if (arg.startsWith("--key=")) flags.key = arg.slice(6);
  if (arg === "--non-interactive") flags.nonInteractive = true;
  if (arg === "--reset") flags.reset = true;
}

if (flags.reset) {
  if (fs.existsSync(ENV_PATH)) {
    fs.unlinkSync(ENV_PATH);
    console.log(c.green("  Config reset."));
  }
}

if (flags.nonInteractive) {
  const vars = {
    OPENROUTER_API_KEY: flags.key || process.env.OPENROUTER_API_KEY || "",
    TRANSCRIPTION_BACKEND: "openrouter",
    PRIVACY_MODE: "standard",
    AGENT_MODEL: "google/gemini-2.5-flash-lite",
    ESCALATION_MODE: "off",
    SINAIN_AGENT: "claude",
    OPENCLAW_WS_URL: "",
    OPENCLAW_HTTP_URL: "",
    PORT: "9500",
    AUDIO_CAPTURE_CMD: "screencapturekit",
    AUDIO_AUTO_START: "true",
    SINAIN_CORE_URL: "http://localhost:9500",
    SINAIN_POLL_INTERVAL: "5",
    SINAIN_HEARTBEAT_INTERVAL: "900",
  };

  if (!vars.OPENROUTER_API_KEY) {
    console.error(c.red("  --key=<key> or OPENROUTER_API_KEY required for non-interactive mode."));
    process.exit(1);
  }

  writeEnv(vars);
  console.log(c.green(`  Config written to ${ENV_PATH}`));
  process.exit(0);
} else {
  runOnboard(flags).catch((err) => {
    console.error(c.red(`  Error: ${err.message}`));
    process.exit(1);
  });
}
