//
//  Generated file. Do not edit.
//  This file is generated by the Flutter tool.
//

import FlutterMacOS
import Foundation

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  // Plugin registrations will be added here by Flutter tooling
}
